// app/layout.tsx

"use client"; // ★★★ 追加: クライアントコンポーネントとしてマーク ★★★
import { Analytics } from '@vercel/analytics/react';
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/Header";
import { usePathname } from "next/navigation"; // ★★★ 追加: usePathnameをインポート ★★★

const inter = Inter({ subsets: ["latin"] });

// Metadataはサーバーコンポーネントでのみ有効なため、ここではコメントアウトまたは削除します。
// 必要であれば、各ページで個別に設定します。
// export const metadata: Metadata = {
//   title: "介護スタッフフィードバック",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname(); // ★★★ 追加: 現在のパスを取得 ★★★
  const showHeader = pathname !== '/'; // ★★★ 追加: ログインページでない場合にtrueになる ★★★

  return (
    <html lang="ja">
      <body className={inter.className}>
        {/* ★★★ 変更: showHeaderがtrueの時だけHeaderを表示し、レイアウトを変更 ★★★ */}
        {showHeader ? (
          <div className="flex flex-col min-h-screen">
            <Header />
            <main className="flex-1 bg-white">
              {children}
            </main>
          </div>
        ) : (
          // ログインページではヘッダーなしのシンプルなレイアウト
          <main>
            {children}
          </main>
        )}
        <Analytics />
      </body>
    </html>
  );
}

